import React,{useEffect,useMemo,useRef,useState}from"react";
import{createRoot}from"react-dom/client";
import{Activity,AlertTriangle,Box,Cable,Database,Download,FileSpreadsheet,FileText,GitBranch,LayoutDashboard,Map,Menu,Plus,Radio,Search,Settings,Upload,X,RefreshCw,Trash2}from"lucide-react";
import L from"leaflet";
import"leaflet/dist/leaflet.css";
import"../src/styles.css";
import * as XLSX from"xlsx";
import{loadCollection,saveCollection}from"./services/dataService";
import{firebaseEnabled}from"./lib/firebase";

const seed={
nodes:[{id:"N001",code:"NODE-BKK-01",name:"Main POP บางกะปิ",type:"Main POP / ODF",lat:13.765,lng:100.647,status:"active",ports:144},{id:"N002",code:"NODE-BKK-02",name:"FDC ลาดพร้าว",type:"FDC Box (Cabinet)",lat:13.781,lng:100.612,status:"active",ports:96},{id:"N003",code:"NODE-BKK-03",name:"Joint รัชดา",type:"Joint Closure / FOSC",lat:13.776,lng:100.574,status:"maintenance",ports:48},{id:"N004",code:"NODE-BKK-04",name:"POP ห้วยขวาง",type:"Substation",lat:13.769,lng:100.579,status:"active",ports:192}],
cables:[{id:"C001",code:"FOC-BKK-001",name:"บางกะปิ - ลาดพร้าว",coreCount:144,status:"normal",source:"N001",dest:"N002",length:6.8},{id:"C002",code:"FOC-BKK-002",name:"ลาดพร้าว - รัชดา",coreCount:96,status:"high_loss",source:"N002",dest:"N003",length:4.2},{id:"C003",code:"FOC-BKK-003",name:"รัชดา - ห้วยขวาง",coreCount:48,status:"normal",source:"N003",dest:"N004",length:2.7}],
cores:[{id:"C001-01",cableId:"C001",coreNo:1,tube:1,color:"Blue",status:"used",fromAsset:"N001",toAsset:"N002"},{id:"C001-02",cableId:"C001",coreNo:2,tube:1,color:"Orange",status:"available",fromAsset:"N001",toAsset:"N002"},{id:"C002-01",cableId:"C002",coreNo:1,tube:1,color:"Blue",status:"fault",fromAsset:"N002",toAsset:"N003"}],
incidents:[{id:"INC-2026-1042",severity:"critical",status:"open",title:"Optical power below threshold",asset:"FOC-BKK-002",opened:"2026-10-07 09:42"},{id:"INC-2026-1041",severity:"medium",status:"investigating",title:"Intermittent loss",asset:"NODE-BKK-03",opened:"2026-10-07 08:16"}],
fttx:[{id:"FTTH-0001",customer:"Customer A",olt:"OLT-BKK-01",port:"1/1/01",node:"N001",status:"active"},{id:"FTTH-0002",customer:"Customer B",olt:"OLT-BKK-01",port:"1/1/02",node:"N002",status:"active"}]
};
const nav=[["Dashboard",LayoutDashboard],["GIS Network",Map],["Fiber Trace",Cable],["Cable & Core",GitBranch],["Infrastructure",Box],["FTTx",Radio],["Incidents",AlertTriangle],["Reports",FileText],["Settings",Settings]];
const uid=p=>p+"-"+Date.now()+"-"+Math.random().toString(36).slice(2,6);

function MapView({nodes,cables,onAdd}){const ref=useRef(null),map=useRef(null);useEffect(()=>{if(!ref.current)return;map.current=L.map(ref.current).setView([13.775,100.61],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map.current);return()=>map.current?.remove()},[]);
useEffect(()=>{if(!map.current)return;map.current.eachLayer(l=>{if(l instanceof L.TileLayer)return;map.current.removeLayer(l)});const by=Object.fromEntries(nodes.map(n=>[n.id,n]));cables.forEach(c=>{const a=by[c.source],b=by[c.dest];if(a&&b)L.polyline([[a.lat,a.lng],[b.lat,b.lng]],{color:c.status==="high_loss"?"#ffad5a":"#15c7f5",weight:5}).bindPopup("<b>"+c.code+"</b><br>"+c.name+"<br>"+c.coreCount+" cores").addTo(map.current)});nodes.forEach(n=>L.circleMarker([n.lat,n.lng],{radius:8,color:"#16c7f2",fillColor:"#07111f",fillOpacity:1,weight:3}).bindPopup("<b>"+n.code+"</b><br>"+n.name+"<br>"+n.status).addTo(map.current))},[nodes,cables]);return <div className="map-wrap"><div className="map-toolbar"><b>GIS Network</b><button onClick={onAdd}><Plus size={15}/> Add Node</button></div><div ref={ref} className="leaflet-map"/></div>}

function App(){const[active,setActive]=useState("Dashboard"),[mobile,setMobile]=useState(false),[q,setQ]=useState(""),[busy,setBusy]=useState(false),[traceCore,setTraceCore]=useState(""),[traceResult,setTraceResult]=useState(null);
const[nodes,setNodes]=useState(seed.nodes),[cables,setCables]=useState(seed.cables),[cores,setCores]=useState(seed.cores),[incidents,setIncidents]=useState(seed.incidents),[fttx,setFttx]=useState(seed.fttx);
useEffect(()=>{(async()=>{setBusy(true);try{const [n,c,cr,i,f]=await Promise.all([loadCollection("nodes",seed.nodes),loadCollection("cables",seed.cables),loadCollection("cores",seed.cores),loadCollection("incidents",seed.incidents),loadCollection("fttx",seed.fttx)]);setNodes(n);setCables(c);setCores(cr);setIncidents(i);setFttx(f)}finally{setBusy(false)}})()},[]);
useEffect(()=>{if(!busy)saveCollection("nodes",nodes)},[nodes]);useEffect(()=>{if(!busy)saveCollection("cables",cables)},[cables]);useEffect(()=>{if(!busy)saveCollection("cores",cores)},[cores]);useEffect(()=>{if(!busy)saveCollection("incidents",incidents)},[incidents]);useEffect(()=>{if(!busy)saveCollection("fttx",fttx)},[fttx]);
const stats=useMemo(()=>({km:cables.reduce((a,c)=>a+Number(c.length||0),0),cores:cables.reduce((a,c)=>a+Number(c.coreCount||0),0),customers:fttx.length,open:incidents.filter(i=>i.status!=="closed").length}),[cables,fttx,incidents]);
const filtered=incidents.filter(i=>(i.title+" "+i.asset+" "+i.id).toLowerCase().includes(q.toLowerCase()));
const addNode=()=>{const code=prompt("Node code","NODE-BKK-"+String(nodes.length+1).padStart(2,"0"));if(!code)return;const name=prompt("Node name","New Fiber Node");const lat=Number(prompt("Latitude","13.77")),lng=Number(prompt("Longitude","100.60"));if(!name||!Number.isFinite(lat)||!Number.isFinite(lng))return;setNodes(v=>[...v,{id:uid("N"),code,name,type:"FDC Box (Cabinet)",lat,lng,status:"active",ports:48}])};
const addIncident=()=>{const title=prompt("Incident title","New fiber fault");if(!title)return;setIncidents(v=>[{id:uid("INC"),severity:"medium",status:"open",title,asset:cables[0]?.code||"N/A",opened:new Date().toLocaleString("sv-SE")},...v])};
const addCore=()=>{if(!cables.length)return;const cableId=prompt("Cable ID",cables[0].id);if(!cables.some(c=>c.id===cableId))return alert("Cable ID not found");const coreNo=Number(prompt("Core number","1"));if(!Number.isInteger(coreNo)||coreNo<1)return;setCores(v=>[...v,{id:uid("CORE"),cableId,coreNo,tube:1,color:"Unspecified",status:"available",fromAsset:cables.find(c=>c.id===cableId).source,toAsset:cables.find(c=>c.id===cableId).dest}])};
const deleteCore=id=>{if(confirm("Delete this core record?"))setCores(v=>v.filter(x=>x.id!==id))};
const exportJSON=()=>{const data={nodes,cables,cores,incidents,fttx,exportedAt:new Date().toISOString()};const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));a.download="ofc-network-backup.json";a.click()};
const exportExcel=()=>{const wb=XLSX.utils.book_new();for(const [name,rows] of Object.entries({Nodes:nodes,Cables:cables,Cores:cores,Incidents:incidents,FTTx:fttx}))XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(rows),name);XLSX.writeFile(wb,"ofc-network-export.xlsx")};
const importExcel=e=>{const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=ev=>{const wb=XLSX.read(ev.target.result,{type:"array"});const sheet=n=>wb.Sheets[n]?XLSX.utils.sheet_to_json(wb.Sheets[n]):null;const n=sheet("Nodes"),c=sheet("Cables"),cr=sheet("Cores"),i=sheet("Incidents"),f=sheet("FTTx");if(n)setNodes(n);if(c)setCables(c);if(cr)setCores(cr);if(i)setIncidents(i);if(f)setFttx(f);alert("Import completed")};reader.readAsArrayBuffer(file);e.target.value=""};
const updateCore=(id,field,value)=>setCores(v=>v.map(c=>c.id===id?{...c,[field]:value}:c));
const trace=()=>{const core=cores.find(c=>c.id===traceCore);if(!core){setTraceResult(null);return}const cable=cables.find(c=>c.id===core.cableId);const from=nodes.find(n=>n.id===core.fromAsset),to=nodes.find(n=>n.id===core.toAsset);const customer=fttx.find(x=>x.node===core.toAsset);setTraceResult({core,cable,from,to,customer})};
return <div className="app"><aside className={"sidebar "+(mobile?"open":"")}><div className="brand"><div className="brand-icon">O</div><div><b>OFC Network</b><small>Asset Manager</small></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={18}/></button></div><nav>{nav.map(([n,I])=><button className={"nav "+(active===n?"active":"")} onClick={()=>{setActive(n);setMobile(false)}} key={n}><I size={18}/><span>{n}</span></button>)}</nav><div className="side-status"><span className="online-dot"/>{firebaseEnabled?"Firebase connected":"Local data engine"}<div>{firebaseEnabled?"Firestore data mode":"Ready for Firebase connection"}</div></div></aside>
<main className="main"><header><button className="mobile-menu" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา cable, node, incident, core..."/></div><label className="icon-btn file-btn" title="Import Excel"><Upload size={18}/><input type="file" accept=".xlsx,.xls" onChange={importExcel}/></label><button className="icon-btn" title="Export JSON" onClick={exportJSON}><Download size={18}/></button><button className="icon-btn" title="Export Excel" onClick={exportExcel}><FileSpreadsheet size={18}/></button><div className="profile"><div className="avatar">A</div><div><b>Administrator</b><small>Network Operations</small></div></div></header>
<section className="content"><div className="page-title"><div><div className="eyebrow"><Activity size={14}/> NETWORK OPERATIONS</div><h1>{active}</h1><p>ระบบบริหารจัดการสินทรัพย์และโครงข่าย Fiber Optic</p></div><div className="actions">{active==="GIS Network"&&<button className="primary" onClick={addNode}><Plus size={16}/> New Node</button>}{active==="Cable & Core"&&<button className="primary" onClick={addCore}><Plus size={16}/> Add Core</button>}{active==="Incidents"&&<button className="primary" onClick={addIncident}><Plus size={16}/> New Incident</button>}</div></div>
{active==="Dashboard"&&<><div className="stats">{[["Fiber Cable",stats.km.toFixed(1)+" km","live"],["Core Capacity",stats.cores.toLocaleString(),"inventory"],["FTTx Customers",stats.customers.toLocaleString(),"active"],["Open Incidents",String(stats.open),"attention"]].map(s=><div className="card stat" key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><em>{s[2]}</em></div>)}</div><div className="workspace"><div className="card"><MapView nodes={nodes} cables={cables} onAdd={addNode}/></div><div className="card events"><div className="section-head"><div><b>Live Network Events</b><span>ข้อมูลจาก Incident / Asset</span></div></div>{filtered.slice(0,6).map(i=><div className="event" key={i.id}><div className={"event-icon "+i.severity}><AlertTriangle size={15}/></div><div><b>{i.id}</b><p>{i.title}</p><small>{i.asset} • {i.opened}</small></div><span className={"pill "+i.severity}>{i.status}</span></div>)}</div></div></>}
{active==="GIS Network"&&<div className="card full"><MapView nodes={nodes} cables={cables} onAdd={addNode}/></div>}
{active==="Infrastructure"&&<div className="card table-card"><h2>Nodes / ODF / FDC</h2>{nodes.map(n=><div className="row" key={n.id}><b>{n.code}</b><span>{n.name}</span><span>{n.type}</span><span>{n.ports} ports</span><span className={"status "+n.status}>{n.status}</span></div>)}</div>}
{active==="Cable & Core"&&<div className="card table-card"><div className="table-title"><div><h2>Cable Routes & Fiber Cores</h2><small>{cores.length} core records • click status to edit</small></div></div><div className="row head"><b>Core</b><span>Cable</span><span>Tube / Color</span><span>Status</span><span>Actions</span></div>{cores.map(c=><div className="row" key={c.id}><b>#{c.coreNo}</b><span>{c.cableId}</span><span>{c.tube} / {c.color}</span><select value={c.status} onChange={e=>updateCore(c.id,"status",e.target.value)}><option>available</option><option>used</option><option>reserved</option><option>fault</option></select><button className="danger-btn" onClick={()=>deleteCore(c.id)}><Trash2 size={14}/></button></div>)}<div className="subtable"><h3>Cable inventory</h3>{cables.map(c=><div className="row" key={c.id}><b>{c.code}</b><span>{c.name}</span><span>{c.coreCount} cores</span><span>{c.length} km</span><span className={"status "+c.status}>{c.status}</span></div>)}</div></div>}
{active==="Incidents"&&<div className="card table-card"><h2>Incident Management</h2>{filtered.map(i=><div className="row" key={i.id}><b>{i.id}</b><span>{i.title}</span><span>{i.asset}</span><span className={"status "+i.severity}>{i.severity}</span><span>{i.status}</span></div>)}</div>}
{active==="FTTx"&&<div className="card table-card"><h2>FTTx Subscribers / OLT Ports</h2>{fttx.map(x=><div className="row" key={x.id}><b>{x.id}</b><span>{x.customer}</span><span>{x.olt}</span><span>{x.port}</span><span className="status active">{x.status}</span></div>)}</div>}
{active==="Fiber Trace"&&<div className="card trace-card"><h2>Fiber Trace</h2><p>Trace ODF → Cable → Core → Joint/FDT → Customer</p><div className="trace-controls"><select value={traceCore} onChange={e=>setTraceCore(e.target.value)}><option value="">เลือก Core...</option>{cores.map(c=><option key={c.id} value={c.id}>{c.id} — {c.cableId} / Core {c.coreNo}</option>)}</select><button className="primary" onClick={trace}>Trace Route</button></div>{traceResult&&<div className="trace-flow"><div className="trace-node"><b>ODF / Source</b><strong>{traceResult.from?.code||"-"}</strong><span>{traceResult.from?.name||"-"}</span></div><div className="trace-arrow">→</div><div className="trace-node"><b>Fiber Cable</b><strong>{traceResult.cable?.code||"-"}</strong><span>{traceResult.cable?.length||0} km</span></div><div className="trace-arrow">→</div><div className="trace-node"><b>Core</b><strong>#{traceResult.core.coreNo}</strong><span>{traceResult.core.status}</span></div><div className="trace-arrow">→</div><div className="trace-node"><b>FDT / Destination</b><strong>{traceResult.to?.code||"-"}</strong><span>{traceResult.to?.name||"-"}</span></div><div className="trace-arrow">→</div><div className="trace-node"><b>Customer</b><strong>{traceResult.customer?.id||"Not linked"}</strong><span>{traceResult.customer?.customer||"No FTTx subscriber"}</span></div></div>}</div>}
{active==="Reports"&&<div className="report-grid"><div className="card metric"><span>Total Nodes</span><strong>{nodes.length}</strong></div><div className="card metric"><span>Total Cable</span><strong>{cables.length}</strong></div><div className="card metric"><span>Core Records</span><strong>{cores.length}</strong></div><div className="card metric"><span>Open Incident</span><strong>{stats.open}</strong></div><div className="card full report-note"><Database size={34}/><h2>Reports & Data Exchange</h2><p>รองรับ JSON backup และ Excel import/export สำหรับ Nodes, Cables, Cores, Incidents และ FTTx</p></div></div>}
{active==="Settings"&&<div className="card placeholder"><Settings size={42}/><h2>System Settings</h2><p>{firebaseEnabled?"เชื่อมต่อ Firestore แล้ว":"ยังใช้ Local mode — ใส่ค่า VITE_FIREBASE_* เพื่อเปิด Firestore"} </p><div className="setting-line"><RefreshCw size={15}/> Data mode: <b>{firebaseEnabled?"Firebase / Firestore":"Browser LocalStorage"}</b></div></div>}
</section></main></div>}
createRoot(document.getElementById("root")).render(<App/>);