import React,{useEffect,useMemo,useState}from"react";import{createRoot}from"react-dom/client";import{Activity,AlertTriangle,Box,Cable,Database,Download,FileText,GitBranch,LayoutDashboard,Map,Menu,Plus,Radio,Search,Settings,Upload,X}from"lucide-react";import L from"leaflet";import"leaflet/dist/leaflet.css";import"./styles.css";

const seed={
nodes:[
{id:"N001",code:"NODE-BKK-01",name:"Main POP บางกะปิ",type:"Main POP / ODF",lat:13.765,lng:100.647,status:"active",ports:144},
{id:"N002",code:"NODE-BKK-02",name:"FDC ลาดพร้าว",type:"FDC Box (Cabinet)",lat:13.781,lng:100.612,status:"active",ports:96},
{id:"N003",code:"NODE-BKK-03",name:"Joint รัชดา",type:"Joint Closure / FOSC",lat:13.776,lng:100.574,status:"maintenance",ports:48},
{id:"N004",code:"NODE-BKK-04",name:"POP ห้วยขวาง",type:"Substation",lat:13.769,lng:100.579,status:"active",ports:192}],
cables:[
{id:"C001",code:"FOC-BKK-001",name:"บางกะปิ - ลาดพร้าว",coreCount:144,status:"normal",source:"N001",dest:"N002",length:6.8},
{id:"C002",code:"FOC-BKK-002",name:"ลาดพร้าว - รัชดา",coreCount:96,status:"high_loss",source:"N002",dest:"N003",length:4.2},
{id:"C003",code:"FOC-BKK-003",name:"รัชดา - ห้วยขวาง",coreCount:48,status:"normal",source:"N003",dest:"N004",length:2.7}],
incidents:[
{id:"INC-2026-1042",severity:"critical",status:"open",title:"Optical power below threshold",asset:"FOC-BKK-002",opened:"2026-10-07 09:42"},
{id:"INC-2026-1041",severity:"medium",status:"investigating",title:"Intermittent loss",asset:"NODE-BKK-03",opened:"2026-10-07 08:16"}],
fttx:[
{id:"FTTH-0001",customer:"Customer A",olt:"OLT-BKK-01",port:"1/1/01",node:"N001",status:"active"},
{id:"FTTH-0002",customer:"Customer B",olt:"OLT-BKK-01",port:"1/1/02",node:"N002",status:"active"}]
};
const load=k=>{try{return JSON.parse(localStorage.getItem("ofc_"+k))||seed[k]}catch{return seed[k]}};
const save=(k,v)=>localStorage.setItem("ofc_"+k,JSON.stringify(v));
const nav=[["Dashboard",LayoutDashboard],["GIS Network",Map],["Cable & Core",GitBranch],["Infrastructure",Box],["FTTx",Radio],["Incidents",AlertTriangle],["Reports",FileText],["Settings",Settings]];

function MapView({nodes,cables,onAdd}){const ref=React.useRef(null);const map=React.useRef(null);
useEffect(()=>{if(!ref.current)return;map.current=L.map(ref.current).setView([13.775,100.61],12);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map.current);return()=>map.current?.remove()},[]);
useEffect(()=>{if(!map.current)return;map.current.eachLayer(l=>{if(l instanceof L.TileLayer)return;map.current.removeLayer(l)});const byId=Object.fromEntries(nodes.map(n=>[n.id,n]));cables.forEach(c=>{const a=byId[c.source],b=byId[c.dest];if(a&&b)L.polyline([[a.lat,a.lng],[b.lat,b.lng]],{color:c.status==="high_loss"?"#ffad5a":"#15c7f5",weight:5,opacity:.9}).bindPopup("<b>"+c.code+"</b><br>"+c.name+"<br>"+c.coreCount+" cores").addTo(map.current)});nodes.forEach(n=>L.circleMarker([n.lat,n.lng],{radius:8,color:"#16c7f2",fillColor:"#07111f",fillOpacity:1,weight:3}).bindPopup("<b>"+n.code+"</b><br>"+n.name+"<br>"+n.status).addTo(map.current));},[nodes,cables]);return <div className="map-wrap"><div className="map-toolbar"><b>GIS Network</b><button onClick={onAdd}><Plus size={15}/> Add Node</button></div><div ref={ref} className="leaflet-map"/></div>}

function App(){const[active,setActive]=useState("Dashboard"),[mobile,setMobile]=useState(false),[q,setQ]=useState("");const[nodes,setNodes]=useState(()=>load("nodes")), [cables,setCables]=useState(()=>load("cables")),[incidents,setIncidents]=useState(()=>load("incidents")),[fttx,setFttx]=useState(()=>load("fttx"));useEffect(()=>save("nodes",nodes),[nodes]);useEffect(()=>save("cables",cables),[cables]);useEffect(()=>save("incidents",incidents),[incidents]);useEffect(()=>save("fttx",fttx),[fttx]);
const stats=useMemo(()=>({km:cables.reduce((a,c)=>a+c.length,0),cores:cables.reduce((a,c)=>a+c.coreCount,0),customers:fttx.length,open:incidents.filter(i=>i.status!=="closed").length}),[cables,fttx,incidents]);
const addNode=()=>{const code=prompt("Node code","NODE-BKK-"+String(nodes.length+1).padStart(2,"0"));if(!code)return;const name=prompt("Node name","New Fiber Node");const lat=Number(prompt("Latitude","13.77")),lng=Number(prompt("Longitude","100.60"));if(!name||!Number.isFinite(lat)||!Number.isFinite(lng))return;setNodes(v=>[...v,{id:"N"+Date.now(),code,name,type:"FDC Box (Cabinet)",lat,lng,status:"active",ports:48}])};
const addIncident=()=>{const title=prompt("Incident title","New fiber fault");if(!title)return;setIncidents(v=>[{id:"INC-"+Date.now(),severity:"medium",status:"open",title,asset:cables[0]?.code||"N/A",opened:new Date().toLocaleString("sv-SE")},...v])};
const exportData=()=>{const blob=new Blob([JSON.stringify({nodes,cables,incidents,fttx},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="ofc-network-backup.json";a.click();URL.revokeObjectURL(a.href)};
const filtered=incidents.filter(i=>(i.title+i.asset+i.id).toLowerCase().includes(q.toLowerCase()));
return <div className="app"><aside className={"sidebar "+(mobile?"open":"")}><div className="brand"><div className="brand-icon">O</div><div><b>OFC Network</b><small>Asset Manager</small></div><button className="mobile-close" onClick={()=>setMobile(false)}><X size={18}/></button></div><nav>{nav.map(([n,I])=><button className={active===n?"nav active":"nav"} onClick={()=>{setActive(n);setMobile(false)}} key={n}><I size={18}/><span>{n}</span></button>)}</nav><div className="side-status"><span className="online-dot"/> Local data engine<div>Ready for Firebase connection</div></div></aside>
<main className="main"><header><button className="mobile-menu" onClick={()=>setMobile(true)}><Menu size={20}/></button><div className="search"><Search size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหา cable, node, incident..."/></div><button className="icon-btn" onClick={exportData}><Download size={18}/></button><div className="profile"><div className="avatar">A</div><div><b>Administrator</b><small>Network Operations</small></div></div></header>
<section className="content"><div className="page-title"><div><div className="eyebrow"><Activity size={14}/> NETWORK OPERATIONS</div><h1>{active}</h1><p>ระบบบริหารจัดการสินทรัพย์และโครงข่าย Fiber Optic</p></div><div className="actions">{active==="GIS Network"&&<button className="primary" onClick={addNode}><Plus size={16}/> New Node</button>}{active==="Incidents"&&<button className="primary" onClick={addIncident}><Plus size={16}/> New Incident</button>}</div></div>
{active==="Dashboard"&&<><div className="stats">{[["Fiber Cable",stats.km.toFixed(1)+" km","live"],["Active Cores",stats.cores.toLocaleString(),"inventory"],["FTTx Customers",stats.customers.toLocaleString(),"active"],["Open Incidents",String(stats.open),"attention"]].map(s=><div className="card stat" key={s[0]}><span>{s[0]}</span><strong>{s[1]}</strong><em>{s[2]}</em></div>)}</div><div className="workspace"><MapView nodes={nodes} cables={cables} onAdd={addNode}/><div className="card events"><div className="section-head"><div><b>Live Network Events</b><span>ข้อมูลจาก Incident / Asset</span></div></div>{filtered.slice(0,6).map(i=><div className="event" key={i.id}><div className={"event-icon "+i.severity}><AlertTriangle size={15}/></div><div><b>{i.id}</b><p>{i.title}</p><small>{i.asset} • {i.opened}</small></div><span className={"pill "+i.severity}>{i.status}</span></div>)}</div></div></>}
{active==="GIS Network"&&<div className="card full"><MapView nodes={nodes} cables={cables} onAdd={addNode}/></div>}
{active==="Infrastructure"&&<div className="card table-card"><h2>Nodes / ODF / FDC</h2>{nodes.map(n=><div className="row" key={n.id}><b>{n.code}</b><span>{n.name}</span><span>{n.type}</span><span>{n.ports} ports</span><span className={"status "+n.status}>{n.status}</span></div>)}</div>}
{active==="Cable & Core"&&<div className="card table-card"><h2>Cable Routes & Fiber Cores</h2>{cables.map(c=><div className="row" key={c.id}><b>{c.code}</b><span>{c.name}</span><span>{c.coreCount} cores</span><span>{c.length} km</span><span className={"status "+c.status}>{c.status}</span></div>)}</div>}
{active==="Incidents"&&<div className="card table-card"><h2>Incident Management</h2>{filtered.map(i=><div className="row" key={i.id}><b>{i.id}</b><span>{i.title}</span><span>{i.asset}</span><span className={"status "+i.severity}>{i.severity}</span><span>{i.status}</span></div>)}</div>}
{active==="FTTx"&&<div className="card table-card"><h2>FTTx Subscribers / OLT Ports</h2>{fttx.map(x=><div className="row" key={x.id}><b>{x.id}</b><span>{x.customer}</span><span>{x.olt}</span><span>{x.port}</span><span className="status active">{x.status}</span></div>)}</div>}
{active==="Reports"&&<div className="report-grid"><div className="card metric"><span>Total Nodes</span><strong>{nodes.length}</strong></div><div className="card metric"><span>Total Cable</span><strong>{cables.length}</strong></div><div className="card metric"><span>Open Incident</span><strong>{stats.open}</strong></div><div className="card metric"><span>FTTx</span><strong>{fttx.length}</strong></div><div className="card full report-note"><Database size={34}/><h2>Data export ready</h2><p>ใช้ปุ่ม Download ด้านบนเพื่อสำรองข้อมูล JSON จาก browser storage</p></div></div>}
{active==="Settings"&&<div className="card placeholder"><Settings size={42}/><h2>System Settings</h2><p>โครงสร้างพร้อมสำหรับเชื่อม Firebase, Authentication และ Telegram ผ่าน environment variables</p></div>}
</section></main></div>}createRoot(document.getElementById("root")).render(<App/>);